src/abudget/money/urls.py
from django.conf.urls import url

from .views import (
    TransactionsView, TransactionsRemoveView,
    IncomeView, IncomeCreateView, IncomeRemoveView,
    UpdateFilterView,
    TransactionsCreateAjaxView,
)

urlpatterns = [
    url(r'^$', TransactionsView.as_view(), name='transactions'),
    url(r'^income/$', IncomeView.as_view(), name='income'),
    url(r'^income/create/$', IncomeCreateView.as_view(), name='income_create'),
    url(r'^income/remove/$', IncomeRemoveView.as_view(), name='income_remove'),
    # url(r'^transactions/create/$', TransactionsCreateView.as_view(), name='transaction_create'),
    url(r'^transactions/remove/$', TransactionsRemoveView.as_view(), name='transaction_remove'),

    url(r'^ajax/transactions/create/$', TransactionsCreateAjaxView.as_view(), name='ajax_transaction_create'),

    url(r'^update_filter/$', UpdateFilterView.as_view(), name='update_filter'),
]

src/abudget/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='money:transactions', permanent=False)),
    url(r'^money/', include('abudget.money.urls', namespace='money')),
    url(r'^users/', include('abudget.users.urls', namespace='users')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/abudget/users/urls.py
from django.conf.urls import url

from .views import (
    UserSettingsView, UserSettingsCategoryAddView,
    UserStatView,
    BudgetActivateView,
)

urlpatterns = [
    url(r'^settings/$', UserSettingsView.as_view(), name='settings'),
    url(r'^settings/category_add/$', UserSettingsCategoryAddView.as_view(), name='settings_category_add'),
    url(r'^settings/budget/activate/$', BudgetActivateView.as_view(), name='settings_budget_activate'),

    url(r'^stat/$', UserStatView.as_view(), name='stat'),
]

src/abudget/money/forms.py
import datetime
import pytz

from django import forms
from django.conf import settings
from django.utils import timezone
from django.utils.translation import ugettext as _

from .models import Transaction, Income


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ('category', 'title', 'amount', 'date')

    def __init__(self, budget=None, creator=None, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.budget = budget
        self.creator = creator
        if self.budget and not self.budget.viewable_by(self.creator):
            raise Exception("Wow")
        self.fields['title'].widget.attrs['placeholder'] = _('Title...')
        self.fields['amount'].widget.attrs['placeholder'] = _('Amount...')
        return

    def clean_category(self, *args, **kwargs):
        category = self.cleaned_data.get('category')
        if category and category.budget != self.budget:
            # TODO
            raise Exception('Wow')
        return category

    def save(self, *args, **kwargs):
        self.instance.budget = self.budget
        self.instance.creator = self.creator
        # who cares about time?..
        self.instance.date = pytz.timezone(settings.TIME_ZONE).localize(
            datetime.datetime.combine(
                self.instance.date, timezone.now().time()
            )
        )
        return super(TransactionForm, self).save(*args, **kwargs)


class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ('category', 'title', 'amount')

    def __init__(self, budget, creator=None, *args, **kwargs):
        super(IncomeForm, self).__init__(*args, **kwargs)
        self.budget = budget
        self.creator = creator
        if self.budget and not self.budget.viewable_by(self.creator):
            raise Exception("Wow")
        self.fields['title'].widget.attrs['placeholder'] = _('Title...')
        self.fields['amount'].widget.attrs['placeholder'] = _('Amount...')
        self.fields['category'].queryset = self.budget.incomecategory_set.all()
        return

    def clean_category(self, *args, **kwargs):
        category = self.cleaned_data.get('category')
        if category and category.budget != self.budget:
            # TODO
            raise Exception('Wow')
        return category

    def save(self, *args, **kwargs):
        self.instance.budget = self.budget
        self.instance.creator = self.creator
        return super(IncomeForm, self).save(*args, **kwargs)

src/abudget/users/forms.py
from django import forms

from abudget.money.models import TransactionCategory


class CreateTransactionCategoryForm(forms.ModelForm):
    class Meta:
        model = TransactionCategory
        fields = ('name', 'parent')

    def __init__(self, budget=None, *args, **kwargs):
        super(CreateTransactionCategoryForm, self).__init__(*args, **kwargs)
        self.budget = budget
        return

    def save(self, *args, **kwargs):
        self.instance.budget = self.budget
        return super(CreateTransactionCategoryForm, self).save(*args, **kwargs)

src/abudget/money/views.py
import datetime
import json

from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.db.models import Sum
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, View
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import ugettext as _

from .forms import TransactionForm, IncomeForm
from .models import Transaction, Income, DEFAULT_FILTER_BY_DATE


class TransactionsView(LoginRequiredMixin, TemplateView):
    template_name = 'money/transactions.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TransactionsView, self).get_context_data(*args, **kwargs)

        stat_spent = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(Sum('amount'))['amount__sum'] or 0

        stat_income = Income.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(Sum('amount'))['amount__sum'] or 0

        stat_balance = stat_income - stat_spent

        context['stat_spent'] = stat_spent
        context['stat_income'] = stat_income
        context['stat_balance'] = stat_balance

        transactions = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        )

        context['new_transaction_form'] = TransactionForm()
        context['transactions'] = transactions
        return context


class TransactionsRemoveView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        transaction = Transaction.objects.get(
            id=request.POST.get('transaction_id'),
            budget=request.budget
        )
        transaction.delete()
        return HttpResponse('ok')


class IncomeView(LoginRequiredMixin, TemplateView):
    template_name = 'money/income.html'

    def get_context_data(self, *args, **kwargs):
        context = super(IncomeView, self).get_context_data(*args, **kwargs)

        context['new_income_form'] = IncomeForm(budget=self.request.budget, creator=self.request.user)
        context['transactions'] = Income.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        )
        return context


class IncomeCreateView(LoginRequiredMixin, CreateView):
    model = Income
    form_class = IncomeForm
    # TODO: exception if form invalid

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super(IncomeCreateView, self).get_form_kwargs(*args, **kwargs)
        # TODO: right workflow here
        # TODO: error handling here
        form_kwargs['budget'] = self.request.budget
        form_kwargs['creator'] = self.request.user
        return form_kwargs

    def get_success_url(self):
        return reverse('money:income')


class UpdateFilterView(View):
    '''
    Sets request.session.filter_by corresponding to user input - date range, in fact
    '''

    def post(self, request, *args, **kwargs):
        redirect_url = request.POST.get('redirect_to')
        today = timezone.now().date()

        filter_by = request.session.get('filter_by', DEFAULT_FILTER_BY_DATE)
        filter_by_date = request.POST.get('date', 'this_month')

        first_day = None
        last_day = None

        if filter_by_date == 'this_month':
            first_day = today.replace(day=1)
            last_day = (first_day + datetime.timedelta(days=45)).replace(day=1) - datetime.timedelta(days=1)
        elif filter_by_date == 'prev_month':
            last_day = today.replace(day=1) - datetime.timedelta(days=1)
            first_day = (last_day - datetime.timedelta(days=10)).replace(day=1)
        elif filter_by_date == 'date_custom':
            # disallow wrong data.
            # TODO: client-side date check
            try:
                first_day = datetime.datetime.strptime(request.POST.get('date_from'), "%Y-%m-%d")
            except (ValueError, TypeError):
                first_day = timezone.now().date()
            try:
                last_day = datetime.datetime.strptime(request.POST.get('date_to'), "%Y-%m-%d")
            except (ValueError, TypeError):
                last_day = timezone.now().date()

        filter_by['date'] = filter_by_date
        if first_day:
            first_day = first_day.strftime("%Y-%m-%d")
        if last_day:
            last_day = last_day.strftime("%Y-%m-%d")
        filter_by['date_from'] = first_day
        filter_by['date_to'] = last_day

        request.session['filter_by'] = filter_by
        request.session.modified = True
        if not redirect_url[0] == '/':
            raise Exception()
        return redirect(redirect_url)


class IncomeRemoveView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        transaction = Income.objects.get(
            id=request.POST.get('transaction_id'),
            budget=request.budget
        )
        transaction.delete()
        return HttpResponse('ok')


class TransactionsCreateAjaxView(LoginRequiredMixin, View):
    def render(self, data):
        return HttpResponse(
            json.dumps(data),
            content_type='application/json'
        )

    def post(self, request, *args, **kwargs):
        result = {
            'status': 'error',
            'message': 'Internal programming error',
            'data': None
        }
        form = TransactionForm(
            data=request.POST,
            budget=request.budget,
            creator=request.user
        )
        if form.is_valid():
            new_trans = form.save()
            result['status'] = 'success'
            result['message'] = _('Transaction added')
            result['data'] = new_trans.get_json_repr()
        else:
            errors = []
            for e in form.errors.values():
                errors.append(e[0])
            result['message'] = 'Error: {}'.format(
                ', '.join(errors)
            )
            result['data'] = form.errors
        return self.render(result)

src/abudget/users/views.py
import datetime

from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db import models
from django.views.generic import TemplateView, CreateView, View
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import ugettext as _

from abudget.money.models import TransactionCategory, Transaction, Income, Budget
from abudget.users.forms import CreateTransactionCategoryForm


class UserSettingsView(LoginRequiredMixin, TemplateView):
    template_name = 'users/settings.html'

    def post(self, request, *args, **kwargs):
        if 'delete_category' in request.POST:
            category_id = request.POST.get('delete_category')
            category = TransactionCategory.objects.get(
                budget=request.budget,
                id=category_id
            )
            for child in category.children.all():
                child.parent = category.parent
                child.save()
            category.delete()
            messages.success(request, 'Category deleted')
        return redirect(reverse('users:settings'))

    def get_context_data(self, *args, **kwargs):
        context = super(UserSettingsView, self).get_context_data(*args, **kwargs)
        context['budgets'] = Budget.objects.filter(
            models.Q(users__in=[self.request.user]) | models.Q(owner=self.request.user)
        )
        return context


class UserSettingsCategoryAddView(LoginRequiredMixin, CreateView):
    model = TransactionCategory
    form_class = CreateTransactionCategoryForm

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super(UserSettingsCategoryAddView, self).get_form_kwargs(*args, **kwargs)
        form_kwargs['budget'] = self.request.budget
        return form_kwargs

    def get_success_url(self):
        return reverse('users:settings')


class UserStatView(LoginRequiredMixin, TemplateView):
    template_name = 'users/stat.html'

    def get_spent_by_category_report_data(self):
        this_period_transactions = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        )
        categories = self.request.budget.get_ordered_categories_list() + [
            TransactionCategory(
                id=None,
                name=_('Without category')
            )
        ]
        for category in categories:
            this_category_transactions = this_period_transactions.filter(category_id=category.id)
            category.report_data = {
                'transactions': this_category_transactions,
                'transactions_count': this_category_transactions.count(),
                'transactions_amount': this_category_transactions.aggregate(
                    models.Sum('amount')
                )['amount__sum'] or 0,
            }

        # TODO: transactions without category
        categories = sorted(categories, key=lambda x: x.report_data['transactions_amount'], reverse=True)
        return categories

    def get_total_amounts(self):
        stat_spent = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(models.Sum('amount'))['amount__sum'] or 0

        stat_income = Income.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(models.Sum('amount'))['amount__sum'] or 0

        stat_balance = stat_income - stat_spent
        return {
            'stat_spent': stat_spent,
            'stat_income': stat_income,
            'stat_balance': stat_balance,
        }

    def get_data_by_months(self):
        months = []
        today = timezone.now().date().replace(day=15)
        year_ago = today - datetime.timedelta(days=365)
        while today > year_ago:
            month_data = {
                'name': today.strftime("%B %Y"),
                'income': Income.objects.filter(
                    budget=self.request.budget,
                    date__year=today.year,
                    date__month=today.month,
                ).aggregate(models.Sum('amount'))['amount__sum'] or 0,
                'spent': Transaction.objects.filter(
                    budget=self.request.budget,
                    date__year=today.year,
                    date__month=today.month,
                ).aggregate(models.Sum('amount'))['amount__sum'] or 0,
                'balance': 0,
            }
            month_data['balance'] = month_data['income'] - month_data['spent']
            month_data['income'] = round(month_data['income'])
            month_data['spent'] = round(month_data['spent'])
            month_data['balance'] = round(month_data['balance'])
            months.append(month_data)
            today -= datetime.timedelta(
                days=30
            )
        return months

    def get_context_data(self, *args, **kwargs):
        context = super(UserStatView, self).get_context_data(*args, **kwargs)
        context['spent_by_category_report_data'] = self.get_spent_by_category_report_data()
        context['total_amounts'] = self.get_total_amounts()
        context['data_by_months'] = self.get_data_by_months()
        return context


class BudgetActivateView(LoginRequiredMixin, View):
    def post(self, *args, **kwargs):
        try:
            budget = Budget.objects.get(
                pk=self.request.POST['budget']
            )
            if not budget.viewable_by(self.request.user):
                raise Budget.DoesNotExist()
            self.request.session['budget_id'] = budget.id
        except Budget.DoesNotExist:
            pass
        return redirect('users:settings')

src/abudget/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'icon.png' %}">
    <title>{% block title %}{% endblock %}</title>

    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'metismenu/dist/metisMenu.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/timeline.css' %}" rel="stylesheet">
    <link href="{% static 'css/abudget_interface.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    {% block extra_head %}{% endblock %}
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">{{ request.budget.name }}</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    {% if request.user.is_authenticated %}
                        <ul class="navbar-nav nav">
                            <li><a href="{% url 'money:transactions' %}"><i class="fa fa-th  fa-fw"></i> {% trans 'Transactions' %}</a></li>
                            <li><a href="{% url 'money:income' %}"><i class="fa fa-smile-o fa-fw"></i> {% trans 'Income' %}</a></li>
                            <li><a href="{% url 'users:stat' %}"><i class="fa fa-bar-chart-o fa-fw"></i> {% trans 'Statistics' %}</a></li>
                            <li><a href="{% url 'users:settings' %}"><i class="fa fa-cog fa-fw"></i> {% trans 'Settings' %}</a></li>
                        </ul>
                    {% endif %}
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'accounts:logout' %}?next=/">{% trans 'Logout' %}</a></li>
                        {% endif %}
                        <li style='padding-top: 10px;'>
                            <form action="/i18n/setlang/" method="post" style='display: inline;' name='lang_form'>
                                {% csrf_token %}
                                <input name="next" type="hidden" value="{{ request.META.PATH_INFO }}" />
                                <button name='language' value='en' class='btn btn-primary btn-sm'>En</button>
                                <button name='language' value='ru' class='btn btn-primary btn-sm'>Ru</button>
                            </form>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        <div id="page-wrapper" class='container-fluid'>
            {% block content %}
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header hidden-xs">{% trans 'Transactions' %}</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
            {% endblock %}
        </div>
    </div>

    {# we don't use CDN to avoid insertion of harmful code to such sensitive application #}
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'metismenu/dist/metisMenu.min.js' %}"></script>
    <script src="{% static 'raphael/raphael-min.js' %}"></script>
    <script src="{% static 'morris.js/morris.min.js' %}"></script>
    <script src="{% static 'jquery.cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/abudget_interface.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>