src/abudget/money/urls.py
from django.conf.urls import url

from .views import (
    TransactionsView, TransactionsRemoveView,
    IncomeView, IncomeCreateView, IncomeRemoveView,
    UpdateFilterView,
    TransactionsCreateAjaxView,
)

urlpatterns = [
    url(r'^$', TransactionsView.as_view(), name='transactions'),
    url(r'^income/$', IncomeView.as_view(), name='income'),
    url(r'^income/create/$', IncomeCreateView.as_view(), name='income_create'),
    url(r'^income/remove/$', IncomeRemoveView.as_view(), name='income_remove'),
    # url(r'^transactions/create/$', TransactionsCreateView.as_view(), name='transaction_create'),
    url(r'^transactions/remove/$', TransactionsRemoveView.as_view(), name='transaction_remove'),

    url(r'^ajax/transactions/create/$', TransactionsCreateAjaxView.as_view(), name='ajax_transaction_create'),

    url(r'^update_filter/$', UpdateFilterView.as_view(), name='update_filter'),
]

src/abudget/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='money:transactions', permanent=False)),
    url(r'^money/', include('abudget.money.urls', namespace='money')),
    url(r'^users/', include('abudget.users.urls', namespace='users')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/abudget/money/models.py
import datetime

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

# TODO: it's bad bad place for this, move it somewhere
DEFAULT_FILTER_BY_DATE = {
    'date': 'this_month',
    'date_from': None,
    'date_to': None,
}


class Budget(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Owner'), related_name='owned_budgets')
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Users'),
        blank=True,
        related_name='participated_budgets'
    )

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return '{} ({})'.format(self.name, self.owner)

    def get_toplevel_categories(self):
        return TransactionCategory.objects.filter(
            budget=self,
            parent=None
        )

    def get_ordered_categories_list(self):
        result = []
        top_level_categories = self.transactioncategory_set.filter(
            parent=None
        )
        for topcat in top_level_categories:
            result.append(topcat)
            result += topcat.get_subcategories_recursive_list()
        return result

    def viewable_by(self, user):
        if self.owner != user and user not in self.users:
            # TODO: add logging here
            return False
        return True


class TransactionBase(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Creator'))
    budget = models.ForeignKey('Budget', verbose_name=_('Budget'))
    title = models.CharField(_('Title'), max_length=300, blank=True)
    amount = models.DecimalField(_('Amount'), max_digits=11, decimal_places=2)
    date = models.DateTimeField(_('Date'), db_index=True, default=timezone.now)

    class Meta:
        abstract = True


class TransactionCategory(models.Model):
    # TODO: orderable
    budget = models.ForeignKey('Budget', verbose_name=_('Budget'))
    parent = models.ForeignKey(
        'self',
        verbose_name=_('Parent'),
        blank=True, null=True, default=None,
        on_delete=models.SET_DEFAULT,
        related_name='children',
    )
    name = models.CharField(_('Name'), max_length=200)

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return self.get_title()

    def get_title(self):
        if self.parent:
            return '{} → {}'.format(self.parent.get_title(), self.name)
        else:
            return self.name

    def get_subcategories_recursive_list(self, level=1):
        result = []
        subcategories_first_level = TransactionCategory.objects.filter(
            parent=self
        )
        for subcat in subcategories_first_level:
            subcat.level = level
            result.append(subcat)
            result += subcat.get_subcategories_recursive_list(level + 1)
        return result

    def save(self, *args, **kwargs):
        if self.parent and self.parent.budget != self.budget:
            raise Exception("Parent category budget not equal to self budget for {}!".format(self))
        return super(TransactionCategory, self).save(*args, **kwargs)


class FilterByDateManager(models.Manager):
    def filter_by_date(self, request):
        'filter out all objects, which have date not in range from request.session.filter_by'
        queryset = self.get_queryset()
        current_timezone = timezone.get_current_timezone()
        filter_by = request.session.get(
            'filter_by',
            DEFAULT_FILTER_BY_DATE
        )
        filter_by_date = filter_by.get('date', 'this_month')
        if filter_by_date == 'this_month' and filter_by.get('date_from') is None:
            # first run after login
            today = timezone.now().date()
            first_day = today.replace(day=1)
            last_day = (first_day + datetime.timedelta(days=45)).replace(day=1) - datetime.timedelta(days=1)
            filter_by['date_from'] = first_day.strftime("%Y-%m-%d")
            filter_by['date_to'] = last_day.strftime("%Y-%m-%d")
        if filter_by_date != 'from_the_beginning':
            first_day = datetime.datetime.strptime(filter_by.get('date_from'), "%Y-%m-%d")
            last_day = datetime.datetime.strptime(
                filter_by.get('date_to') or '',
                "%Y-%m-%d"
            ) + datetime.timedelta(days=1)
            first_day = current_timezone.localize(first_day)
            last_day = current_timezone.localize(last_day)
            if first_day:
                queryset = queryset.filter(
                    date__gte=first_day,
                )
            if last_day:
                queryset = queryset.filter(
                    date__lte=last_day
                )
        return queryset


class Transaction(TransactionBase):
    category = models.ForeignKey(
        'TransactionCategory',
        verbose_name=_('Category'),
        blank=True, null=True, default=None,
        on_delete=models.SET_DEFAULT
    )

    objects = FilterByDateManager()

    class Meta:
        ordering = ('-date',)

    def get_short_descr(self):
        if self.title:
            return "{} ({})".format(self.title, self.amount)
        return self.amount

    def __str__(self):
        return '[{}#{}] {} at {}'.format(self.budget.id, self.budget.name, self.amount, self.date)

    def get_json_repr(self):
        fields_to_save = ('id', 'category', 'title', 'amount', 'date')
        result = {}
        for f in fields_to_save:
            result[f] = str(getattr(self, f))
        return result


class IncomeCategory(models.Model):
    # TODO: orderable
    budget = models.ForeignKey('Budget', verbose_name=_('Budget'))
    name = models.CharField(_('Name'), max_length=200)

    def __str__(self):
        return self.name


class Income(TransactionBase):
    category = models.ForeignKey(
        'IncomeCategory',
        verbose_name=_('Income'),
        blank=True, null=True, default=None,
        on_delete=models.SET_DEFAULT
    )

    objects = FilterByDateManager()

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return '[{}#{}] {} at {}'.format(self.budget.id, self.budget.name, self.amount, self.date)

src/abudget/money/forms.py
import datetime
import pytz

from django import forms
from django.conf import settings
from django.utils import timezone
from django.utils.translation import ugettext as _

from .models import Transaction, Income


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ('category', 'title', 'amount', 'date')

    def __init__(self, budget=None, creator=None, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.budget = budget
        self.creator = creator
        if self.budget and not self.budget.viewable_by(self.creator):
            raise Exception("Wow")
        self.fields['title'].widget.attrs['placeholder'] = _('Title...')
        self.fields['amount'].widget.attrs['placeholder'] = _('Amount...')
        return

    def clean_category(self, *args, **kwargs):
        category = self.cleaned_data.get('category')
        if category and category.budget != self.budget:
            # TODO
            raise Exception('Wow')
        return category

    def save(self, *args, **kwargs):
        self.instance.budget = self.budget
        self.instance.creator = self.creator
        # who cares about time?..
        self.instance.date = pytz.timezone(settings.TIME_ZONE).localize(
            datetime.datetime.combine(
                self.instance.date, timezone.now().time()
            )
        )
        return super(TransactionForm, self).save(*args, **kwargs)


class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ('category', 'title', 'amount')

    def __init__(self, budget, creator=None, *args, **kwargs):
        super(IncomeForm, self).__init__(*args, **kwargs)
        self.budget = budget
        self.creator = creator
        if self.budget and not self.budget.viewable_by(self.creator):
            raise Exception("Wow")
        self.fields['title'].widget.attrs['placeholder'] = _('Title...')
        self.fields['amount'].widget.attrs['placeholder'] = _('Amount...')
        self.fields['category'].queryset = self.budget.incomecategory_set.all()
        return

    def clean_category(self, *args, **kwargs):
        category = self.cleaned_data.get('category')
        if category and category.budget != self.budget:
            # TODO
            raise Exception('Wow')
        return category

    def save(self, *args, **kwargs):
        self.instance.budget = self.budget
        self.instance.creator = self.creator
        return super(IncomeForm, self).save(*args, **kwargs)

src/abudget/money/views.py
import datetime
import json

from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.db.models import Sum
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, View
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import ugettext as _

from .forms import TransactionForm, IncomeForm
from .models import Transaction, Income, DEFAULT_FILTER_BY_DATE


class TransactionsView(LoginRequiredMixin, TemplateView):
    template_name = 'money/transactions.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TransactionsView, self).get_context_data(*args, **kwargs)

        stat_spent = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(Sum('amount'))['amount__sum'] or 0

        stat_income = Income.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(Sum('amount'))['amount__sum'] or 0

        stat_balance = stat_income - stat_spent

        context['stat_spent'] = stat_spent
        context['stat_income'] = stat_income
        context['stat_balance'] = stat_balance

        transactions = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        )

        context['new_transaction_form'] = TransactionForm()
        context['transactions'] = transactions
        return context


class TransactionsRemoveView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        transaction = Transaction.objects.get(
            id=request.POST.get('transaction_id'),
            budget=request.budget
        )
        transaction.delete()
        return HttpResponse('ok')


class IncomeView(LoginRequiredMixin, TemplateView):
    template_name = 'money/income.html'

    def get_context_data(self, *args, **kwargs):
        context = super(IncomeView, self).get_context_data(*args, **kwargs)

        context['new_income_form'] = IncomeForm(budget=self.request.budget, creator=self.request.user)
        context['transactions'] = Income.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        )
        return context


class IncomeCreateView(LoginRequiredMixin, CreateView):
    model = Income
    form_class = IncomeForm
    # TODO: exception if form invalid

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super(IncomeCreateView, self).get_form_kwargs(*args, **kwargs)
        # TODO: right workflow here
        # TODO: error handling here
        form_kwargs['budget'] = self.request.budget
        form_kwargs['creator'] = self.request.user
        return form_kwargs

    def get_success_url(self):
        return reverse('money:income')


class UpdateFilterView(View):
    '''
    Sets request.session.filter_by corresponding to user input - date range, in fact
    '''

    def post(self, request, *args, **kwargs):
        redirect_url = request.POST.get('redirect_to')
        today = timezone.now().date()

        filter_by = request.session.get('filter_by', DEFAULT_FILTER_BY_DATE)
        filter_by_date = request.POST.get('date', 'this_month')

        first_day = None
        last_day = None

        if filter_by_date == 'this_month':
            first_day = today.replace(day=1)
            last_day = (first_day + datetime.timedelta(days=45)).replace(day=1) - datetime.timedelta(days=1)
        elif filter_by_date == 'prev_month':
            last_day = today.replace(day=1) - datetime.timedelta(days=1)
            first_day = (last_day - datetime.timedelta(days=10)).replace(day=1)
        elif filter_by_date == 'date_custom':
            # disallow wrong data.
            # TODO: client-side date check
            try:
                first_day = datetime.datetime.strptime(request.POST.get('date_from'), "%Y-%m-%d")
            except (ValueError, TypeError):
                first_day = timezone.now().date()
            try:
                last_day = datetime.datetime.strptime(request.POST.get('date_to'), "%Y-%m-%d")
            except (ValueError, TypeError):
                last_day = timezone.now().date()

        filter_by['date'] = filter_by_date
        if first_day:
            first_day = first_day.strftime("%Y-%m-%d")
        if last_day:
            last_day = last_day.strftime("%Y-%m-%d")
        filter_by['date_from'] = first_day
        filter_by['date_to'] = last_day

        request.session['filter_by'] = filter_by
        request.session.modified = True
        if not redirect_url[0] == '/':
            raise Exception()
        return redirect(redirect_url)


class IncomeRemoveView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        transaction = Income.objects.get(
            id=request.POST.get('transaction_id'),
            budget=request.budget
        )
        transaction.delete()
        return HttpResponse('ok')


class TransactionsCreateAjaxView(LoginRequiredMixin, View):
    def render(self, data):
        return HttpResponse(
            json.dumps(data),
            content_type='application/json'
        )

    def post(self, request, *args, **kwargs):
        result = {
            'status': 'error',
            'message': 'Internal programming error',
            'data': None
        }
        form = TransactionForm(
            data=request.POST,
            budget=request.budget,
            creator=request.user
        )
        if form.is_valid():
            new_trans = form.save()
            result['status'] = 'success'
            result['message'] = _('Transaction added')
            result['data'] = new_trans.get_json_repr()
        else:
            errors = []
            for e in form.errors.values():
                errors.append(e[0])
            result['message'] = 'Error: {}'.format(
                ', '.join(errors)
            )
            result['data'] = form.errors
        return self.render(result)

src/abudget/money/templates/money/filter_by_block.html
{% load i18n %}

<div class='col-lg-3'>
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-thumb-tack"></i> {% trans 'Filter by' %}
        </div>
        <div class="panel-body">
            <form action="{% url 'money:update_filter' %}" method='post'>
                {% csrf_token %}
                <input type='hidden' name='redirect_to' value="{{ request.META.PATH_INFO }}" />
                <select name='date' class='form-control'>
                    <option value='this_month' {% if request.session.filter_by.date == 'this_month' %}selected{% endif %}>{% trans 'This month' %}</option>
                    <option value='prev_month' {% if request.session.filter_by.date == 'prev_month' %}selected{% endif %}>{% trans 'Previous month' %}</option>
                    <option value='from_the_beginning' {% if request.session.filter_by.date == 'from_the_beginning' %}selected{% endif %}>{% trans 'From the beginning' %}</option>
                    <option value='date_custom' {% if request.session.filter_by.date == 'date_custom' %}selected{% endif %}>{% trans 'Custom range' %}</option>
                </select>

                <div class="input-group">
                  <input type="text" class="form-control" placeholder="{% trans 'from date (empty for today)' %}" value="{{ request.session.filter_by.date_from|default:'' }}" name="date_from">
                  <input type="text" class="form-control" placeholder="{% trans 'to date (empty for today)' %}" value="{{ request.session.filter_by.date_to|default:'' }}" name="date_to">
                </div>

                <button type='submit' class='btn btn-primary big-button'>{% trans 'Apply' %}</button>
            </form>
        </div>
    </div>
</div>

src/abudget/money/templates/money/income.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}{% trans 'Income' %}{% endblock %}

{% block content %}

    <div class='row'>
        <h1 class="page-header">{% trans 'Income' %}</h1>
    
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> {% trans 'Enter Income Transaction' %}
                </div>
                <div class="panel-body income-add-form">
                    <form action="{% url 'money:income_create' %}" method='post' class='form-horisontal' id='id_income_form'>
                        {% csrf_token %}

                        {{ new_income_form|crispy }}

                        <button class='btn btn-primary' type='submit' id='id_income_form_submit'>{% trans 'Save income' %}</button>
                    </form>
                </div>
            </div>
            <!-- /.panel -->
        </div>

        <div class='col-lg-6'>
            {% for trans in transactions %}
                <div class='transaction-item row'>
                    <i class='remove-income-transaction fa fa-times-circle' data-transaction-id='{{ trans.id }}'></i>
                    <span class='category col-lg-6'>{{ trans.category }} ({{ trans.creator }})</span>
                    <span class='amount col-lg-3'>{{ trans.amount }}</span>
                    <span class='date col-lg-2'>{{ trans.date|naturalday }} {{ trans.date.time|time }}</span>
                    <span class='title col-lg-12'>{{ trans.title }}</span>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/abudget/money/templates/money/transactions.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load i18n %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}{% trans 'Transactions' %}{% endblock %}

{% block content %}
    <div class='row'>
        <h1 class="page-header">{% trans 'Transactions' %}</h1>
    
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-plus-circle"></i> {% trans 'Enter transaction' %}
                </div>
                <div class="panel-body transaction-add-form">
                    <form action="{% url 'money:ajax_transaction_create' %}" method='post' class='form-horisontal' id='id_transaction_form'>
                        {% csrf_token %}
                        <input type='hidden' name='category' value='' id='id_selected_category' />

                        <div class="panel panel-default settings-panel">
                            <div class="panel-body">
                                <input type='text' name='date' value="{% now 'Y-m-d' %}" />
                            </div>
                        </div>

                        {% for toplevel_category in request.budget.get_toplevel_categories %}
                            <div class="btn-group" id='transaction_category_selector'>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ toplevel_category }} <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li class='category_item' data-category-id='{{ toplevel_category.id }}'><a href="#">{{ toplevel_category }}</a></li>
                                    {% for category in toplevel_category.get_subcategories_recursive_list %}
                                        <li class='category_item category_level_{{ category.level }}' data-category-id='{{ category.id }}'><a>{{ category.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endfor %}

                        <p class="form-control-static" id="selected-category-field">...</p>

                        <input class="numberinput form-control col-lg-6" id="id_amount" name="amount" placeholder="{% trans 'Amount' %}..." type="text">
                        {{ new_transaction_form.title|attr:"class:form-control"}}<br/>
                        <button class='btn btn-primary big-button' type='submit' id='id_transaction_form_submit'>{% trans 'Save transaction' %}</button>
                    </form>
                </div>
            </div>
            <!-- /.panel -->
        </div>

        <div class='col-lg-3'>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-thumb-tack"></i> {% trans 'Stat' %}
                </div>
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item row">
                            <span class="col-lg-8">{% trans 'Income' %}</span>
                            <span class="col-lg-4 righted">{{ stat_income|intcomma }}</span>
                        </li>
                        <li class="list-group-item row">
                            <span class="col-lg-8">{% trans 'Spent' %}</span>
                            <span class="col-lg-4 righted">{{ stat_spent|intcomma }}</span>
                        </li>
                        <li class="list-group-item row">
                            <span class="col-lg-8">{% trans 'Balance' %}</span>
                            <span class="col-lg-4 righted">{{ stat_balance|intcomma }}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        {% include "money/filter_by_block.html" %}

        <div class="clearfix"></div>

        <div class='col-lg-6'>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-th-list"></i> {% trans 'History' %}
                </div>
                <div class="panel-body" id='id_transactions_list'>
                    {% for trans in transactions %}
                        <div class='transaction-item row'>
                            <i class='remove-transaction fa fa-times-circle' data-transaction-id='{{ trans.id }}'></i>
                            <span class='category col-lg-6'>{{ trans.category.get_title }}</span>
                            <span class='amount col-lg-3'>{{ trans.amount }}</span>
                            <span class='date col-lg-2'>{{ trans.date.date|naturalday }}</span>
                            <span class='title col-lg-12'>{{ trans.title }}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}