src/abudget/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='money:transactions', permanent=False)),
    url(r'^money/', include('abudget.money.urls', namespace='money')),
    url(r'^users/', include('abudget.users.urls', namespace='users')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/abudget/users/urls.py
from django.conf.urls import url

from .views import (
    UserSettingsView, UserSettingsCategoryAddView,
    UserStatView,
    BudgetActivateView,
)

urlpatterns = [
    url(r'^settings/$', UserSettingsView.as_view(), name='settings'),
    url(r'^settings/category_add/$', UserSettingsCategoryAddView.as_view(), name='settings_category_add'),
    url(r'^settings/budget/activate/$', BudgetActivateView.as_view(), name='settings_budget_activate'),

    url(r'^stat/$', UserStatView.as_view(), name='stat'),
]

src/abudget/users/forms.py
from django import forms

from abudget.money.models import TransactionCategory


class CreateTransactionCategoryForm(forms.ModelForm):
    class Meta:
        model = TransactionCategory
        fields = ('name', 'parent')

    def __init__(self, budget=None, *args, **kwargs):
        super(CreateTransactionCategoryForm, self).__init__(*args, **kwargs)
        self.budget = budget
        return

    def save(self, *args, **kwargs):
        self.instance.budget = self.budget
        return super(CreateTransactionCategoryForm, self).save(*args, **kwargs)

src/abudget/users/views.py
import datetime

from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db import models
from django.views.generic import TemplateView, CreateView, View
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import ugettext as _

from abudget.money.models import TransactionCategory, Transaction, Income, Budget
from abudget.users.forms import CreateTransactionCategoryForm


class UserSettingsView(LoginRequiredMixin, TemplateView):
    template_name = 'users/settings.html'

    def post(self, request, *args, **kwargs):
        if 'delete_category' in request.POST:
            category_id = request.POST.get('delete_category')
            category = TransactionCategory.objects.get(
                budget=request.budget,
                id=category_id
            )
            for child in category.children.all():
                child.parent = category.parent
                child.save()
            category.delete()
            messages.success(request, 'Category deleted')
        return redirect(reverse('users:settings'))

    def get_context_data(self, *args, **kwargs):
        context = super(UserSettingsView, self).get_context_data(*args, **kwargs)
        context['budgets'] = Budget.objects.filter(
            models.Q(users__in=[self.request.user]) | models.Q(owner=self.request.user)
        )
        return context


class UserSettingsCategoryAddView(LoginRequiredMixin, CreateView):
    model = TransactionCategory
    form_class = CreateTransactionCategoryForm

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super(UserSettingsCategoryAddView, self).get_form_kwargs(*args, **kwargs)
        form_kwargs['budget'] = self.request.budget
        return form_kwargs

    def get_success_url(self):
        return reverse('users:settings')


class UserStatView(LoginRequiredMixin, TemplateView):
    template_name = 'users/stat.html'

    def get_spent_by_category_report_data(self):
        this_period_transactions = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        )
        categories = self.request.budget.get_ordered_categories_list() + [
            TransactionCategory(
                id=None,
                name=_('Without category')
            )
        ]
        for category in categories:
            this_category_transactions = this_period_transactions.filter(category_id=category.id)
            category.report_data = {
                'transactions': this_category_transactions,
                'transactions_count': this_category_transactions.count(),
                'transactions_amount': this_category_transactions.aggregate(
                    models.Sum('amount')
                )['amount__sum'] or 0,
            }

        # TODO: transactions without category
        categories = sorted(categories, key=lambda x: x.report_data['transactions_amount'], reverse=True)
        return categories

    def get_total_amounts(self):
        stat_spent = Transaction.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(models.Sum('amount'))['amount__sum'] or 0

        stat_income = Income.objects.filter_by_date(self.request).filter(
            budget=self.request.budget,
        ).aggregate(models.Sum('amount'))['amount__sum'] or 0

        stat_balance = stat_income - stat_spent
        return {
            'stat_spent': stat_spent,
            'stat_income': stat_income,
            'stat_balance': stat_balance,
        }

    def get_data_by_months(self):
        months = []
        today = timezone.now().date().replace(day=15)
        year_ago = today - datetime.timedelta(days=365)
        while today > year_ago:
            month_data = {
                'name': today.strftime("%B %Y"),
                'income': Income.objects.filter(
                    budget=self.request.budget,
                    date__year=today.year,
                    date__month=today.month,
                ).aggregate(models.Sum('amount'))['amount__sum'] or 0,
                'spent': Transaction.objects.filter(
                    budget=self.request.budget,
                    date__year=today.year,
                    date__month=today.month,
                ).aggregate(models.Sum('amount'))['amount__sum'] or 0,
                'balance': 0,
            }
            month_data['balance'] = month_data['income'] - month_data['spent']
            month_data['income'] = round(month_data['income'])
            month_data['spent'] = round(month_data['spent'])
            month_data['balance'] = round(month_data['balance'])
            months.append(month_data)
            today -= datetime.timedelta(
                days=30
            )
        return months

    def get_context_data(self, *args, **kwargs):
        context = super(UserStatView, self).get_context_data(*args, **kwargs)
        context['spent_by_category_report_data'] = self.get_spent_by_category_report_data()
        context['total_amounts'] = self.get_total_amounts()
        context['data_by_months'] = self.get_data_by_months()
        return context


class BudgetActivateView(LoginRequiredMixin, View):
    def post(self, *args, **kwargs):
        try:
            budget = Budget.objects.get(
                pk=self.request.POST['budget']
            )
            if not budget.viewable_by(self.request.user):
                raise Budget.DoesNotExist()
            self.request.session['budget_id'] = budget.id
        except Budget.DoesNotExist:
            pass
        return redirect('users:settings')

src/abudget/users/templates/users/settings.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Settings' %}{% endblock %}

{% block content %}
    <div class='row'>
        <h1 class="page-header">{% trans 'Settings' %}</h1>
    
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> {% trans 'Transactions categories' %}
                </div>
                <div class="panel-body">
                    <form action="{% url 'users:settings_category_add' %}" method='post' class='form-inline'>
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" id="id_category_name" placeholder="{% trans 'new category name' %}" name='name' required>
                        </div>
                        <div class="form-group">
                            <select name='parent' class="form-control" >
                                <option value=''>(select parent category here or leave empty)</option>
                                {% for cat in request.budget.transactioncategory_set.all %}
                                    <option value="{{ cat.id }}">{{ cat }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-default">{% trans 'Add category' %}</button>
                    </form>

                    <br />

                    <form action="#" method='post' class='form-inline' onSubmit='return confirm("Sure?");'>
                        {% csrf_token %}
                        <ul class="list-group">
                            {% for cat in request.budget.transactioncategory_set.all %}
                                <li class="list-group-item">
                                    {{ cat }}
                                    <button class="btn btn-danger btn-xs" type='submit' name='delete_category' value='{{ cat.id }}'>delete</button>
                                </li>
                            {% endfor %}
                        </ul>
                    </form>
                </div>
            </div>
            <!-- /.panel -->
        </div>


        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> {% trans 'Budgets' %}
                </div>
                <div class="panel-body">
                    <table>
                        <form action="{% url 'users:settings_budget_activate' %}" method='post' class='form-inline'>
                            {% csrf_token %}
                            <ul class="list-group">
                            {% for budget in budgets %}
                                <li class="list-group-item">
                                    {{ budget }}
                                    {% if request.budget != budget %}
                                        <button class="btn btn-primary btn-sm" type='submit' name='budget' value='{{ budget.id }}'>{% trans 'Activate' %}</button>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                        </form>
                    </table>
                </div>
            </div>
            <!-- /.panel -->
        </div>

    </div>
{% endblock %}

src/abudget/users/templates/users/stat.html
{% extends 'base.html' %}
{% load humanize %}
{% load i18n %}

{% block title %}{% trans 'Stat' %}{% endblock %}

{% block content %}
    <div class='row'>
        <h1 class="page-header hidden-xs">{% trans 'Stat' %}</h1>
    
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> {% trans 'Spent by categories' %}
                </div>
                <div class="panel-body">
                    <table class='table'>
                        <tr>
                            <td></td>
                            <th>{% trans 'Category' %}</th>
                            <th>#{% trans 'count' %}</th>
                            <th>#{% trans 'amount' %}</th>
                        </tr>
                        {% for category in spent_by_category_report_data %}
                            {% if category.report_data.transactions_count > 0 %}
                                <tr class='spent_by_categories_table_row' data-morris-index="{{ forloop.counter0 }}" data-morris-display="true" data-morris-title="{{ category }}" data-morris-value="{{ category.report_data.transactions_amount }}">
                                    <td>
                                        <label class='label label-info hideshow-label'>hide</label>
                                    </td>
                                    <td class='title'>
                                        {{ category }}
                                        <label class='label label-info category-details-label' data-details-id="category_details_{{ category.id }}">...</label>
                                    </td>
                                    <td class='righted'>{{ category.report_data.transactions_count }}</td>
                                    <td class='righted' class='value'>{{ category.report_data.transactions_amount|intcomma }}</td>
                                </tr>
                                <tr class='stat_category_details' id='category_details_{{ category.id }}'>
                                    <td></td>
                                    <td colspan='3'>
                                        {% for transaction in category.report_data.transactions %}
                                            <div class='stat-transaction-row'>
                                                <div class='date'>{{ transaction.date.date }}</div>
                                                {{ transaction.title|default:"?" }}
                                                <div class='pull-right'>{{ transaction.amount }}</div><br/>
                                            </div>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                    
                </div>
            </div>
            <!-- /.panel -->
        </div>

        <div class='col-lg-3'>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> {% trans 'Spent by categories graph' %}
                </div>
                <div class="panel-body">
                    <ul class="list-group spent-by-categories-totals">
                      <li class="list-group-item">
                        <span class="badge">{{ total_amounts.stat_income|intcomma }}</span>
                        {% trans 'Total income' %}
                      </li>
                      <li class="list-group-item">
                        <span class="badge">{{ total_amounts.stat_spent|intcomma }}</span>
                        {% trans 'Total spent' %}
                      </li>
                      <li class="list-group-item">
                        <span class="badge">{{ total_amounts.stat_balance|intcomma }}</span>
                        {% trans 'Total balance' %}
                      </li>
                    </ul>
                    <div id='spent_by_categories_canvas'></div>
                </div>
            </div>
        </div>

        {% include "money/filter_by_block.html" %}

        <div class='col-lg-3'>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> {% trans 'By months' %}
                </div>
                <div class="panel-body">
                    <table class='table table-striped'>
                        <tr>
                            <th>{% trans 'Month' %}</th>
                            <th>{% trans 'Income' %}</th>
                            <th>{% trans 'Spent' %}</th>
                            <th>{% trans 'Balance' %}</th>
                        </tr>
                        {% for month_data in data_by_months %}
                            <tr>
                                <td>{{ month_data.name }}</td>
                                <td class='righted'>{{ month_data.income|intcomma }}</td>
                                <td class='righted'>{{ month_data.spent|intcomma }}</td>
                                <td class='righted'>{{ month_data.balance|intcomma }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>

    </div>
{% endblock %}


{% block extra_js %}
    <script>
        $(document).bind('ready', function on_stat_page_load() {
            function prepare_spent_by_categories_data() {
                var data = [];
                $("tr.spent_by_categories_table_row").each(function() {
                    var $th = $(this);
                    var row = {
                        label: $th.data('morris-title'),
                        value: $th.data('morris-value'),
                    };
                    if ($th.data('morris-display') == true) {
                        data.push(row);
                    };
                });
                return data;
            };

            var spent_by_categories_chart = Morris.Donut({
                element: 'spent_by_categories_canvas',
                data: prepare_spent_by_categories_data(),
                resize: true
            });

            $("tr.spent_by_categories_table_row").bind('mouseover', function spent_by_categories_table_row_mouseover() {
                var $th = $(this);
                $th.parent().find('tr').css('background-color', '');
                spent_by_categories_chart.select($th.data('morris-index'));
                $th.css('background-color', 'whitesmoke');
            });

            $("tr.spent_by_categories_table_row .hideshow-label").bind('click', function spent_by_categories_table_row_click() {
                var $th = $(this);
                var $tr = $th.parent().parent();  // parent <tr>
                if ($tr.data('morris-display') == true) {
                    $tr.data('morris-display', false);
                    $tr.find('td').css('color', 'silver');
                    $th.text('show');
                } else {
                    $tr.data('morris-display', true);
                    $tr.find('td').css('color', 'black');
                    $th.text('hide');
                };
                spent_by_categories_chart.setData(prepare_spent_by_categories_data());
            });


            $(".category-details-label").bind('click', function category_toggle_details() {
                var $th = $(this);
                var target_id = $th.data('details-id');
                $('#' + target_id).toggle();
            });
        });
    </script>
{% endblock %}